class AuthService(object):
    def __init__(self):
        ...

    def hash_password(self, password: str)
        ...

    def login(self):
        ...

    def logout(self):
        ...

    def generate_token(self):
        ...
